version: "3"

services:
  node:
    build:
      context: ./node
    image: wellintona/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node app.js
    container_name: node
    volumes:
      - ./node:/usr/src/app
    networks:
      - nodenet
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    tty: true
    volumes:
      - "./mysql/db/data:/var/lib/mysql"
      - "./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./mysql/db/sql:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - "3306:3306"
    networks:
      - nodenet

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on:
      - node

networks:
  nodenet:
    driver: bridge
